<?php

namespace Rutatiina\Item\Seeders;

use Illuminate\Database\Seeder;
use Rutatiina\Item\Models\Item;

class ItemCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            'Food' => [
                'Grain Products',
                'Coffee',
                'Nut & Kernel',
                'Water/ Juices/ Drinks',
                'Dried Goods',
                'Grocery',
                'Canned Food',
                'Alcoholic Beverages',
                'Fish and sea food',
                'Meat',
                'Milk and eggs',
                'Cheese',
                'Ready meal',
                'Bread and pastries',
                'Frozen products',
                'Vegetables and greens',
                'Fruits and berries',
                'Sausages',
                'Tea',
            ],
            'Home Appliances' => [
                'Household Appliances',
                'Personal Care Appliances',
                'Commercial Appliances',
                'Major Appliances',
                'Home Appliance Parts',
                'Kitchen Appliances',
            ],
            'Computer & Office' => [
                'Storage Devices',
                'Laptops',
                'Servers',
                'Demo Board & Accessories',
                'Desktops',
                'Tablets',
                'Computer Cables & Connectors',
                'Office Software',
                'Mini PC',
                'Computer Peripherals',
                'Tablet Accessories',
                'Networking',
                'Computer Components',
                'Device Cleaners',
                'Office Electronics',
                'Industrial Computer & Accessories',
                'Mouse & Keyboards',
                'Laptop Accessories',
                'Laptop Parts',
                'Tablet Parts'
            ],
            'Home Improvement' => [
                'Electrical Equipments & Supplies',
                'Hardware',
                'Kitchen Fixtures',
                'Plumbing',
                'Painting Supplies & Wall Treatments',
                'Family Intelligence System',
                'Home Appliances',
                'Lights & Lighting',
                'Building Supplies',
                'Bathroom Fixtures',
            ],
            'Home & Garden' => [
                'Garden Supplies',
                'Household Merchandises',
                'Home Textile',
                'Home Storage & Organization',
                'Home Decor',
                'Arts,Crafts & Sewing',
                'Kitchen,Dining & Bar',
                'Household Cleaning',
                'Festive & Party Supplies',
                'Bathroom Products',
                'Pet Products'
            ],
            'Sports & Entertainment' => [
                'Sports Accessories',
                'Sports Bags',
                'Team Sports',
                'Sports Clothing',
                'Swimming',
                'Cycling',
                'Sneakers',
                'Running',
                'Roller Skates, Skateboards & Scooters',
                'Bowling',
                'Entertainment',
                'Racquet Sports',
                'Golf',
                'Fitness & Body Building',
                'Other Sports & Entertainment',
                'Skiing & Snowboarding',
                'Water Sports',
                'Shooting',
                'Horse Racing',
                'Hunting',
                'Fishing',
                'Camping & Hiking',
                'Musical Instruments',
            ],
            'Education & Office Supplies' => [
                'Paper',
                'Desk Accessories & Organizer',
                'Art Supplies',
                'Presentation Supplies',
                'Books & Magazines',
                'Stationery Sticker',
                'Mail & Shipping Supplies',
                'Writing & Correction Supplies',
                'Calendars, Planners & Cards',
                'Labels, Indexes & Stamps',
                'Filing Products',
                'Notebooks & Writing Pads',
                'School & Educational Supplies',
                'Tapes, Adhesives & Fasteners',
                'Office Binding Supplies',
                'Cutting Supplies',
            ],
            'Toys & Hobbies' => [
                'Stress Relief Toy',
                'Pools & Water Fun',
                'Popular Toys',
                'Hobby & Collectibles',
                'Stuffed Animals & Plush',
                'Arts & Crafts, DIY toys',
                'High Tech Toys',
                'Kid\'s Party',
                'Building & Construction Toys',
                'Play Vehicles & Models',
                'Ride On Toys',
                'Action & Toy Figures',
                'Puzzles & Games',
                'Dolls & Accessories',
                'Novelty & Gag Toys',
                'Model Building',
                'Remote Control Toys',
                'Diecasts & Toy Vehicles',
                'Baby & Toddler Toys',
                'Pretend Play',
                'Outdoor Fun & Sports',
                'Electronic Toys',
                'Classic Toys',
                'Learning & Education'
            ],
            'Security & Protection' => [
                'Security Alarm',
                'Building Automation',
                'Smart Card System',
                'Door Intercom',
                'Workplace Safety Supplies',
                'Fire Protection',
                'Video Surveillance',
                'Safes',
                'Self Defense Supplies',
                'Access Control',
                'Public Broadcasting',
                'Roadway Safety',
                'Transmission & Cables',
                'IoT Devices',
                'Security Inspection Device',
                'Lightning Protection',
                'Emergency Kits'
            ],
            'Automobiles & Motorcycles' => [
                'Car Lights',
                'Car Repair Tools',
                'ATV,RV,Boat & Other Vehicle',
                'Travel & Roadway Product',
                'Car Wash & Maintenance',
                'Motorcycle Accessories & Parts',
                'Car Electronics',
                'Auto Replacement Parts',
                'Exterior Accessories',
                'Interior Accessories',
            ],
            'Lights & Lighting' => [
                'Lighting Accessories',
                'Holiday Lighting',
                'Ceiling Lights & Fans',
                'Lamps & Shades',
                'Special Engineering Lighting',
                'Under Cabinet Lights',
                'Outdoor Lighting',
                'Light Bulbs',
                'Novelty Lighting',
                'Professional Lighting',
                'Commercial Lighting',
                'LED Lamps',
                'Book Lights',
                'Night Lights',
                'Vanity Lights',
                'LED Lighting',
                'Portable Lighting',
            ],
            'Consumer Electronics' => [
                'VR/AR Devices',
                'Speakers',
                'Sports & Action Video Cameras',
                'Earphones & Headphones',
                '360° Video Cameras & Accessories',
                'Home Electronic Accessories',
                'Power Source',
                'Live Equipment',
                'HIFI Devices',
                'Robot',
                'Wearable Devices',
                'Video Games',
                'Camera & Photo',
                'Accessories & Parts',
                'Portable Audio & Video',
                'Home Audio & Video',
                'Electronic Cigarettes',
                'Smart Electronics'
            ],
            'Beauty & Health' => [
                'Sanitary Paper',
                'Oral Hygiene',
                'Skin Care',
                'Makeup',
                'Shaving & Hair Removal',
                'Beauty Equipment',
                'Health Care',
                'Bath & Shower',
                'Hair Care & Styling',
                'Fragrances & Deodorants',
                'Tattoo & Body Art',
                'Sex Products',
                'Tools & Accessories',
                'Nails Art & Tools',
                'Men\'s Grooming',
                'Skin Care Tools',
                'Beauty Essentials',
            ],
            'Shoes' => [
                'Men\'s Vulcanize Shoes',
                'Women\'s Boots',
                'Women\'s Flats',
                'Women\'s Pumps',
                'Men\'s Casual Shoes',
                'Women\'s Vulcanize Shoes',
                'Men\'s Boots',
                'Shoe Accessories',
                'Women\'s Shoes',
                'Men\'s Shoes',
            ],
            'Electronic Components & Supplies' => [
                'Electronic Data Systems',
                'Electronics Stocks',
                'Active Components',
                'Electronics Production Machinery',
                'Electronic Accessories & Supplies',
                'Optoelectronic Displays',
                'Passive Components',
                'Other Electronic Components',
                'Electronic Signs',
                'EL Products',
            ],
            'Cellphones & Telecommunications' => [
                'Mobile Phone Accessories',
                'Mobile Phone Parts',
                'Phone Bags & Cases',
                'Walkie Talkie Parts & Accessories',
                'Communication Equipments',
                'Cellphones',
                'Feature Phones',
                'Walkie Talkie',
                'Refurbished Phones',
                'iPhones',

            ],
            'Tools' => [
                'Power Tools',
                'Welding & Soldering Supplies',
                'Abrasives',
                'Woodworking Machinery & Parts',
                'Welding Equipment',
                'Measurement & Analysis Instruments',
                'Abrasive Tools',
                'Riveter Guns',
                'Hand & Power Tool Accessories',
                'Lifting Tools & Accessories',
                'Hand Tools',
                'Tool Parts',
                'Construction Tools',
                'Garden Tools',
                'Tool Sets',
                'Tool Organizers',
                'Machine Tools & Accessories',
            ],
            'Mother & Kids' => [
                'Baby Stroller & Accessories',
                'Toilet Training',
                'Car Seats & Accessories',
                'Baby Food',
                'Pregnancy & Maternity',
                'Baby Souvenirs',
                'Baby Furniture',
                'Matching Family Outfits',
                'kids&Baby Accessories',
                'Children\'s Shoes',
                'Nappy Changing',
                'Baby Shoes',
                'Girls\' Baby Clothing',
                'Boys\' Baby Clothing',
                'Feeding',
                'Activity & Gear',
                'Safety Equipment',
                'Baby Care',
                'Boys\' Clothing',
                'Girls\' Clothing',
                'Baby Bedding',
            ],
            'Furniture' => [
                'Café Furniture',
                'Furniture Parts',
                'Furniture Accessories',
                'Home Furniture',
                'Office Furniture',
                'Commercial Furniture',
                'Outdoor Furniture',
                'Children Furniture',
                'Bar Furniture',
            ],
            'Jewelry & Accessories' => [
                'Beads & Jewelry Making',
                'Jewelry making',
                'Customized Jewelry',
                'Fine Jewelry',
                'Wedding & Engagement Jewelry',
                'Earrings',
                'Necklaces & Pendants',
                'Bracelets & Bangles',
                'Jewelry Sets & More',
                'Rings',
            ],
            'Watches' => [
                'Women\'s Bracelet Watches',
                'Lover\'s Watches',
                'Children\'s Watches',
                'Women\'s Watches',
                'Men\'s Watches',
                'Pocket & Fob Watches',
                'Watch Accessories',
            ],
            'Luggage & Bags' => [
                'Coin Purses & Holders',
                'Luggage & Travel Bags',
                'Bag Parts & Accessories',
                'Backpacks',
                'Wallets',
                'Functional Bags',
                'Kids & Baby\'s Bags',
                'Men\'s Bags',
                'Women\'s Bags',
            ],
            'Hair Extensions & Wigs' => [
                'Human Hair Weaves',
                'Synthetic Extensions',
                'Hair Braids',
                'Synthetic Wigs',
                'Salon Hair Supply Chain',
                'Hair Extensions',
                'DIY Wigs',
                'Hair Salon Tools & Accessories',
                'Lace Wigs',
                'Hair Pieces',
            ],
            'Virtual Goods' => [
                'Prepaid Digital Code',
                'Tickets',
                'Cartão de presente',
                'Coupons',
                'Software & Games',
            ],
            'Novelty & Special Use' => [
                'Work Wear & Uniforms',
                'Exotic Apparel',
                'Costumes & Accessories',
                'Traditional & Cultural Wear',
                'Stage & Dance Wear',
            ],
            'Weddings & Events' => [
                'Dresses',
                'Bridesmaid Dresses',
                'Mother of the Bride Dresses',
                'Quinceanera Dresses',
                'Homecoming Dresses',
                'Celebrity-Inspired Dresses',
                'Wedding Party Dress',
                'Wedding Dresses',
                'Cocktail Dresses',
                'Evening Dresses',
                'Prom Dresses',
                'Wedding Accessories',
            ],
            'Women\'s Clothing' => [
                'Rompers',
                'Bodysuits',
                'Pants & Capris',
                'Dress',
                'Skirt',
                'Jeans',
                'Muslim Fashion',
                'Bottoms',
                'Plus size clothes',
                'Swimsuit',
                'Women Tops',
                'Blouses & Shirts',
                'Dresses',
                'Jumpsuits',
                'Sweaters',
                'Suits & Sets',
                'Jackets & Coats',
                'Tops & Tees',
                'Hoodies & Sweatshirts',
            ],
            'Men\'s Clothing' => [
                'Men\'s Sets',
                'Pants',
                'Tops & Tees',
                'Board Shorts',
                'Sweaters',
                'Suits & Blazers',
                'Shirts',
                'Jackets & Coats',
                'Jeans',
                'Casual Shorts',
                'Hoodies & Sweatshirts',
            ],
            'Apparel Accessories' => [
                'Women\'s Hair Accessories',
                'Women\'s Belts',
                'Women\'s Hats',
                'Women\'s Scarves',
                'Women\'s Glasses',
                'Women\'s Gloves',
                'Women\'s Accessories',
                'Men\'s Glasses',
                'Men\'s Gloves',
                'Men\'s Scarves',
                'Men\'s Hats',
                'Men\'s Ties & Handkerchiefs',
                'Men\'s Belts',
                'Men\'s Accessories',
                'Girl\'s Accessories',
                'Garment Fabrics & Accessories',
                'Boy\'s Accessories',
            ],
            'Underwear & Sleepwears' => [
                'Men\'s Socks',
                'Women\'s Sleepwears',
                'Women\'s Socks & Hosiery',
                'Women\'s Intimates',
                'Men\'s Underwear',
                'Men\'s Sleep & Lounge',
                'Women\'s panties',
            ],
        ];
    }
}
